### ISSUE TITLE
Codebeispiel enthält fehlerhaften Code

### ISSUE THREAD

**Issue by miiirj** [stefanhuber/Serverseitige-Softwareentwicklung#2]
Hallo,
ich bin gerade das "Arbeiten mit SQLite" Tutorial durchgegangen und mir ist aufgefallen, dass wenn ich das Codebeispiel so ausführe wie es dort steht, einen `PHP Fatal error: Uncaught Error. Call to undefined function PDO()` bekomme.
https://github.com/stefanhuber/serverseitige-softwareentwicklung/blob/master/content/tutorials/04.md#test

Ich habe den Fehler für mich gefixt indem ich statt:
```php
$pdo = PDO("sqlite:my_test_db.sqlite");
```
diesen Code verwendet habe
```php 
$pdo = new PDO("sqlite:my_test_db.sqlite");
```

**Comment by stefanhuber** [comment]
Hey super! Da hast du einen Fehler gefunden! Deine Lösung wäre genau meine Intention gewesen. Würdest du einen Pull Request durchführen? In der Commit Message könntest du auch #2 angeben, dann wäre die Issue referenziert.
